### ISSUE TITLE
Small improvements

### ISSUE THREAD

**Issue by TyVik** [NameRec/longbow#16]
https://github.com/NameRec/longbow/blob/4160ae1dbb0f78ea8a227192f24d65c72e0b560d/src/longbow/views.py#L49

I think 'radio' would be enough.

**Comment by NameRec** [comment]
Hm... In requirements explicitly specified that:

> ...Тесты имеют определенный порядок вопросов. У вопроса может быть **один или несколько вариантов правильных ответов**...
>

It's guys is very cunning ;-)
In addition, if the answer was one, I would simplify the data structure. In particular, there would not be a need for a TestPassingAnswer model.
